###TEST#####
############
############




---
- name: Apply ISO 27001:2023 Security Controls on Windows Servers
  hosts: windows_servers
  become: yes
  vars:
    audit_policy_path: 'HKLM:\Software\Policies\Microsoft\Windows\Audit'
    security_policy_path: 'C:\Windows\security\templates\secure_sch_template.inf'
    event_log_settings:
      - log: "Application"
        max_size: 10485760  # 10 MB
        retention: "OverwriteAsNeeded"
      - log: "Security"
        max_size: 15728640  # 15 MB
        retention: "OverwriteAsNeeded"
      - log: "System"
        max_size: 10485760  # 10 MB
        retention: "OverwriteAsNeeded"
    users_to_remove: 
      - Guest
      - DefaultAccount
    allowed_users:
      - Administrator
      - johndoe  # Replace with actual usernames
  tasks:

    - name: Ensure Windows Firewall is enabled
      win_feature:
        name: "Windows-Firewall"
        state: present

    - name: Set password policies
      win_user_right:
        name: "MinimumPasswordLength"
        setting: "14"
      win_user_right:
        name: "PasswordHistorySize"
        setting: "24"
      win_user_right:
        name: "MaximumPasswordAge"
        setting: "60"

    - name: Configure audit policy for system events
      win_audit_policy:
        category: System
        subcategory: Security State Change
        audit_flag: Success,Failure

    - name: Configure event log size and retention
      win_eventlog:
        log_name: "{{ item.log }}"
        maximum_size_in_bytes: "{{ item.max_size }}"
        retention: "{{ item.retention }}"
      loop: "{{ event_log_settings }}"

    - name: Remove unnecessary user accounts
      win_user:
        name: "{{ item }}"
        state: absent
      loop: "{{ users_to_remove }}"

    - name: Ensure allowed users are in the Administrators group
      win_group_membership:
        name: Administrators
        members: "{{ allowed_users }}"
        state: present

    - name: Disable unnecessary services
      win_service:
        name: "{{ item }}"
        start_mode: disabled
        state: stopped
      loop:
        - RemoteRegistry
        - Telnet
        - SNMP

    - name: Apply security templates
      win_template:
        src: "{{ security_policy_path }}"
        dest: 'C:\Windows\security\templates\applied_security_template.inf'

    - name: Enable BitLocker on system drives
      win_feature:
        name: BitLocker
        state: present
      win_bitlocker:
        mount_point: "C:"
        encryption_method: XtsAes256
        protectors:
          - tpm
          - password

    - name: Configure remote desktop settings
      win_feature:
        name: RDS-RD-Server
        state: present
      win_shell:
        cmd: "Set-ItemProperty -Path 'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server' -Name 'fDenyTSConnections' -Value 1"

    - name: Enable Windows Defender Antivirus
      win_feature:
        name: Windows-Defender-Features
        state: present
      win_service:
        name: WinDefend
        state: started
        start_mode: automatic

    - name: Configure audit logs for specific directories
      win_acl_inheritance:
        path: 'C:\SensitiveData'
        user: SYSTEM
        permission: Modify
        type: allow
      win_audit_rule:
        path: 'C:\SensitiveData'
        principal: SYSTEM
        audit_type: Success,Failure
        permissions: Modify

    - name: Enable and configure Windows Update settings
      win_service:
        name: wuauserv
        start_mode: automatic
        state: started
      win_shell:
        cmd: "Set-ItemProperty -Path 'HKLM:\\Software\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Name 'NoAutoUpdate' -Value 0"

    - name: Restrict access to system utilities (e.g., cmd, powershell)
      win_feature:
        name: AppLocker
        state: present
      win_applocker_policy:
        name: BlockCmdPowershell
        policy: |
          <RuleCollection Type="Exe" EnforcementMode="Enabled">
            <FilePublisherRule Id="e5d71fb7-1c4b-4adf-839b-5d6b3b5dcf8d" Name="BlockCmdAndPowershell" Description="Blocks cmd.exe and powershell.exe">
              <Conditions>
                <FilePublisherCondition>
                  <PublisherName>*</PublisherName>
                  <ProductName>*</ProductName>
                  <BinaryName>cmd.exe; powershell.exe</BinaryName>
                </FilePublisherCondition>
              </Conditions>
              <Action Type="Deny"/>
            </FilePublisherRule>
          </RuleCollection>

    - name: Configure time synchronization settings
      win_shell:
        cmd: "w32tm /config /manualpeerlist:time.windows.com /syncfromflags:manual /reliable:YES /update"
      win_service:
        name: W32Time
        state: started
        start_mode: automatic

    - name: Configure security auditing
      win_audit_policy:
        category: Account Logon
        subcategory: Credential Validation
        audit_flag: Success,Failure

    - name: Disable SMBv1
      win_feature:
        name: FS-SMB1
        state: absent

    - name: Apply file integrity monitoring (FIM)
      win_audit_policy:
        category: Detailed Tracking
        subcategory: File System
        audit_flag: Success,Failure
      win_audit_rule:
        path: 'C:\CriticalFiles'
        principal: SYSTEM
        audit_type: Success,Failure
        permissions: FullControl
